### PR TITLE
Use XHR2 instead of Fetch API for progress display on some browsers

### PR DESCRIPTION
**Pull request by zhangjk95**
Stream-based Fetch API is currently not a standard (and even not a draft). Therefore, the loading progress is not shown on some browsers (such as firefox). So I use XHR2 instead of Fetch API on browsers which supports XHR2 with blob response. It can make the loading progress be shown on most of modern browsers.

### CODE REVIEW

**Comment by Kiikurage** [comment]
Thanks for your PR! I'll merge this after #445 is merged.

**Comment by zhangjk95** [comment]
I updated this branch with the newest version.

**Comment by Kiikurage** [comment]
Thank you!

**Comment by zhangjk95** [comment]
I'm sorry. I forgot to commit the compiled files that includes the changes in this PR. Please compile it, thanks!

**Comment by Kiikurage** [comment]
No problem! thanks.

**Pull request merged**
